---
title: "Plotting RECHARGE trends"
output: html_document
date: "2023-10-11"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyselect)
require(here)
require(wesanderson)
require(scales) # for pretty_breaks()
```

Plot up some of the RECHARGE patterns through time

# Bring in the data

```{r}
montip_change <- read_csv(here("generated_data/recharge_montipChangeT12.csv"))

percHard <- read_csv(here("generated_data/recharge_comm_mat.csv"))
```


# Boxplot of differences at T = 12

```{r}
# pdf(here("figs/Montipora_box_change12.pdf"), width = 6, height = 3)
    
montip_change %>% 
  ggplot(aes(x = Herb_TRT, y = Change_Montip12)) +
  geom_boxplot(aes(color = Nutrient_Trt)) +
  geom_point(aes(color = Nutrient_Trt)) +
  facet_wrap(~Disturbance_Trt) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Fish exclusion treatment") +
  ylab("Change in Montipora (%T12-%T0)") +
  scale_color_manual(name = "Nutrients",
                     values = c(wes_palette(name = "Royal1", n = 2))) +
  theme_classic() # -> tChangeplot


# dev.off()

```

# Montipora time series

## All plots

```{r}
# pdf(here("figs/Montipora_timeseriesT12.pdf"), width = 7, height = 6)

montip_change %>% 
  pivot_longer(cols = c(`0`, `1`, `2`, `3`, `4`, `6`, `8`, `9`, `10`, `11`, `12`), values_to = "Percent_cover", names_to = "Time_point") %>%
  mutate(Block_Plot_Herb = paste0(Block_Plot, Herb_TRT)) %>% 
  mutate(Time_point = as.numeric(Time_point)) %>% 
  ggplot(aes(x = Time_point, y = Percent_cover, group = Block_Plot_Herb, color = Nutrient_Trt)) + 
  geom_line(aes(linetype = Disturbance_Trt)) +
  facet_grid(Herb_TRT ~ Disturbance_Trt) +
  theme_bw() +
  geom_vline(xintercept = 2.5, color = "yellow") +
  ylab("Montipora percent cover") +
  guides(linetype = guide_legend(title = "Disturbance")) +
  scale_x_continuous(breaks= pretty_breaks()) +
  xlab("Time point") +
  scale_color_manual(name = "Nutrients",
                     values = c(wes_palette(name = "Royal1", n = 2)))

# dev.off()
```

## Treatment means

```{r}
# pdf(here("figs/Montipora_meantimeseriesT12.pdf"), width = 7, height = 6)

montip_change %>% 
  pivot_longer(cols = c(`0`, `1`, `2`, `3`, `4`, `6`, `8`, `9`, `10`, `11`, `12`), values_to = "Percent_cover", names_to = "Time_point") %>%
  mutate(Block_Plot_Herb = paste0(Block_Plot, Herb_TRT)) %>% 
  mutate(Time_point = as.numeric(Time_point)) %>% 
  group_by(Time_point, Disturbance_Trt, Nutrient_Trt, Herb_TRT) %>% 
  summarize(Avg_percent_cover = mean(Percent_cover)) %>% 
  ggplot(aes(x = Time_point, y = Avg_percent_cover, color = Nutrient_Trt)) + 
  geom_line(aes(linetype = Disturbance_Trt)) +
  facet_grid(Herb_TRT ~ Disturbance_Trt) +
  theme_bw() +
  ylab("Average Montipora percent cover") +
  xlab("Time point") +
  geom_vline(xintercept = 2.5, color = "yellow") +
  scale_color_manual(name = "Nutrients",
                     values = c(wes_palette(name = "Royal1", n = 2))) +
  guides(linetype = guide_legend(title = "Disturbance")) +
  scale_x_continuous(breaks= pretty_breaks())

# dev.off()
```

# Time series of 4 main corals

```{r}
# pdf(here("figs/FourCoral_meantimeseriesT12.pdf"), width = 7, height = 6)

percHard %>%
  mutate(Block_Plot_Herb = paste0(Block_Plot, Herb_TRT)) %>% 
  mutate(Time_point = as.numeric(Time_point)) %>% 
  filter(Time_point < 13) %>% 
  group_by(Time_point, Disturbance_Trt, Nutrient_Trt, Herb_TRT) %>% 
  summarize(Montipora = mean(Montipora_spp),
            Porites = mean(Porites_spp),
            Acropora = mean(Acropora_spp),
            Pocillopora = mean(Pocillopora_spp)) %>% 
  pivot_longer(cols = c("Montipora", "Acropora", "Pocillopora", "Porites"), names_to = "Coral", values_to = "Avg_perc_cover") %>% 
  # optional--not sure if this is what we want to focus on?
  #filter(Disturbance_Trt == "Disturbed") %>% 
  ggplot(aes(x = Time_point, y = Avg_perc_cover, color = Coral)) + 
  geom_line(aes(linetype = Nutrient_Trt)) +
  facet_grid(Herb_TRT ~ Disturbance_Trt) +
  theme_bw() +
  ylab("Average percent cover") +
  xlab("Time point") +
  geom_vline(xintercept = 2.5, color = "yellow") +
  scale_color_manual(name = "Coral",
                     values = c(wes_palette(name = "GrandBudapest1", n = 4))) +
  guides(linetype = guide_legend(title = "Nutrients")) +
  scale_x_continuous(breaks= pretty_breaks()) +
  ylim(0, 40)
  
# dev.off()
```




